# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kw/Desktop/StealthDrone-Purdue-

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kw/Desktop/StealthDrone-Purdue-

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kw/Desktop/StealthDrone-Purdue-/CMakeFiles /home/kw/Desktop/StealthDrone-Purdue-/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kw/Desktop/StealthDrone-Purdue-/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ydlidar_driver

# Build rule for target.
ydlidar_driver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ydlidar_driver
.PHONY : ydlidar_driver

# fast build rule for target.
ydlidar_driver/fast:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/build
.PHONY : ydlidar_driver/fast

#=============================================================================
# Target rules for targets named unit_tests_runner

# Build rule for target.
unit_tests_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_tests_runner
.PHONY : unit_tests_runner

# fast build rule for target.
unit_tests_runner/fast:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/build
.PHONY : unit_tests_runner/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/uninstall.dir/build.make third_party/tinyxml2/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named xmltest

# Build rule for target.
xmltest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 xmltest
.PHONY : xmltest

# fast build rule for target.
xmltest/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/xmltest.dir/build.make third_party/tinyxml2/CMakeFiles/xmltest.dir/build
.PHONY : xmltest/fast

#=============================================================================
# Target rules for targets named tinyxml2_static

# Build rule for target.
tinyxml2_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tinyxml2_static
.PHONY : tinyxml2_static

# fast build rule for target.
tinyxml2_static/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/tinyxml2_static.dir/build.make third_party/tinyxml2/CMakeFiles/tinyxml2_static.dir/build
.PHONY : tinyxml2_static/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ContinuousSubmit.dir/build.make third_party/tinyxml2/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ContinuousCoverage.dir/build.make third_party/tinyxml2/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ContinuousTest.dir/build.make third_party/tinyxml2/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ContinuousBuild.dir/build.make third_party/tinyxml2/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ContinuousMemCheck.dir/build.make third_party/tinyxml2/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/Nightly.dir/build.make third_party/tinyxml2/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/NightlyTest.dir/build.make third_party/tinyxml2/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/NightlyUpdate.dir/build.make third_party/tinyxml2/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/Continuous.dir/build.make third_party/tinyxml2/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/NightlyBuild.dir/build.make third_party/tinyxml2/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/NightlyStart.dir/build.make third_party/tinyxml2/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/NightlyMemoryCheck.dir/build.make third_party/tinyxml2/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/NightlyMemCheck.dir/build.make third_party/tinyxml2/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ExperimentalStart.dir/build.make third_party/tinyxml2/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ContinuousConfigure.dir/build.make third_party/tinyxml2/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/NightlyCoverage.dir/build.make third_party/tinyxml2/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ExperimentalUpdate.dir/build.make third_party/tinyxml2/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ExperimentalConfigure.dir/build.make third_party/tinyxml2/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ExperimentalCoverage.dir/build.make third_party/tinyxml2/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ExperimentalBuild.dir/build.make third_party/tinyxml2/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/NightlyConfigure.dir/build.make third_party/tinyxml2/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ExperimentalTest.dir/build.make third_party/tinyxml2/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ExperimentalMemCheck.dir/build.make third_party/tinyxml2/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/Experimental.dir/build.make third_party/tinyxml2/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/NightlySubmit.dir/build.make third_party/tinyxml2/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ExperimentalSubmit.dir/build.make third_party/tinyxml2/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ContinuousStart.dir/build.make third_party/tinyxml2/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f third_party/tinyxml2/CMakeFiles/ContinuousUpdate.dir/build.make third_party/tinyxml2/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named minigzip

# Build rule for target.
minigzip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minigzip
.PHONY : minigzip

# fast build rule for target.
minigzip/fast:
	$(MAKE) -f third_party/zlib/CMakeFiles/minigzip.dir/build.make third_party/zlib/CMakeFiles/minigzip.dir/build
.PHONY : minigzip/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f third_party/zlib/CMakeFiles/example.dir/build.make third_party/zlib/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named zlibstatic

# Build rule for target.
zlibstatic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlibstatic
.PHONY : zlibstatic

# fast build rule for target.
zlibstatic/fast:
	$(MAKE) -f third_party/zlib/CMakeFiles/zlibstatic.dir/build.make third_party/zlib/CMakeFiles/zlibstatic.dir/build
.PHONY : zlibstatic/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f third_party/zlib/CMakeFiles/zlib.dir/build.make third_party/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named example64

# Build rule for target.
example64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example64
.PHONY : example64

# fast build rule for target.
example64/fast:
	$(MAKE) -f third_party/zlib/CMakeFiles/example64.dir/build.make third_party/zlib/CMakeFiles/example64.dir/build
.PHONY : example64/fast

#=============================================================================
# Target rules for targets named minigzip64

# Build rule for target.
minigzip64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minigzip64
.PHONY : minigzip64

# fast build rule for target.
minigzip64/fast:
	$(MAKE) -f third_party/zlib/CMakeFiles/minigzip64.dir/build.make third_party/zlib/CMakeFiles/minigzip64.dir/build
.PHONY : minigzip64/fast

#=============================================================================
# Target rules for targets named ydlidar_test

# Build rule for target.
ydlidar_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ydlidar_test
.PHONY : ydlidar_test

# fast build rule for target.
ydlidar_test/fast:
	$(MAKE) -f samples/CMakeFiles/ydlidar_test.dir/build.make samples/CMakeFiles/ydlidar_test.dir/build
.PHONY : ydlidar_test/fast

#=============================================================================
# Target rules for targets named cpp_rsc

# Build rule for target.
cpp_rsc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cpp_rsc
.PHONY : cpp_rsc

# fast build rule for target.
cpp_rsc/fast:
	$(MAKE) -f third_party/cpp_rsc/src/CMakeFiles/cpp_rsc.dir/build.make third_party/cpp_rsc/src/CMakeFiles/cpp_rsc.dir/build
.PHONY : cpp_rsc/fast

#=============================================================================
# Target rules for targets named dronecode_sdk

# Build rule for target.
dronecode_sdk: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk
.PHONY : dronecode_sdk

# fast build rule for target.
dronecode_sdk/fast:
	$(MAKE) -f core/CMakeFiles/dronecode_sdk.dir/build.make core/CMakeFiles/dronecode_sdk.dir/build
.PHONY : dronecode_sdk/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_action

# Build rule for target.
dronecode_sdk_action: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_action
.PHONY : dronecode_sdk_action

# fast build rule for target.
dronecode_sdk_action/fast:
	$(MAKE) -f plugins/action/CMakeFiles/dronecode_sdk_action.dir/build.make plugins/action/CMakeFiles/dronecode_sdk_action.dir/build
.PHONY : dronecode_sdk_action/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_calibration

# Build rule for target.
dronecode_sdk_calibration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_calibration
.PHONY : dronecode_sdk_calibration

# fast build rule for target.
dronecode_sdk_calibration/fast:
	$(MAKE) -f plugins/calibration/CMakeFiles/dronecode_sdk_calibration.dir/build.make plugins/calibration/CMakeFiles/dronecode_sdk_calibration.dir/build
.PHONY : dronecode_sdk_calibration/fast

#=============================================================================
# Target rules for targets named camera_definition_files

# Build rule for target.
camera_definition_files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 camera_definition_files
.PHONY : camera_definition_files

# fast build rule for target.
camera_definition_files/fast:
	$(MAKE) -f plugins/camera/CMakeFiles/camera_definition_files.dir/build.make plugins/camera/CMakeFiles/camera_definition_files.dir/build
.PHONY : camera_definition_files/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_camera

# Build rule for target.
dronecode_sdk_camera: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_camera
.PHONY : dronecode_sdk_camera

# fast build rule for target.
dronecode_sdk_camera/fast:
	$(MAKE) -f plugins/camera/CMakeFiles/dronecode_sdk_camera.dir/build.make plugins/camera/CMakeFiles/dronecode_sdk_camera.dir/build
.PHONY : dronecode_sdk_camera/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_follow_me

# Build rule for target.
dronecode_sdk_follow_me: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_follow_me
.PHONY : dronecode_sdk_follow_me

# fast build rule for target.
dronecode_sdk_follow_me/fast:
	$(MAKE) -f plugins/follow_me/CMakeFiles/dronecode_sdk_follow_me.dir/build.make plugins/follow_me/CMakeFiles/dronecode_sdk_follow_me.dir/build
.PHONY : dronecode_sdk_follow_me/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_gimbal

# Build rule for target.
dronecode_sdk_gimbal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_gimbal
.PHONY : dronecode_sdk_gimbal

# fast build rule for target.
dronecode_sdk_gimbal/fast:
	$(MAKE) -f plugins/gimbal/CMakeFiles/dronecode_sdk_gimbal.dir/build.make plugins/gimbal/CMakeFiles/dronecode_sdk_gimbal.dir/build
.PHONY : dronecode_sdk_gimbal/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_info

# Build rule for target.
dronecode_sdk_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_info
.PHONY : dronecode_sdk_info

# fast build rule for target.
dronecode_sdk_info/fast:
	$(MAKE) -f plugins/info/CMakeFiles/dronecode_sdk_info.dir/build.make plugins/info/CMakeFiles/dronecode_sdk_info.dir/build
.PHONY : dronecode_sdk_info/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_log_files

# Build rule for target.
dronecode_sdk_log_files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_log_files
.PHONY : dronecode_sdk_log_files

# fast build rule for target.
dronecode_sdk_log_files/fast:
	$(MAKE) -f plugins/log_files/CMakeFiles/dronecode_sdk_log_files.dir/build.make plugins/log_files/CMakeFiles/dronecode_sdk_log_files.dir/build
.PHONY : dronecode_sdk_log_files/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_mission

# Build rule for target.
dronecode_sdk_mission: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_mission
.PHONY : dronecode_sdk_mission

# fast build rule for target.
dronecode_sdk_mission/fast:
	$(MAKE) -f plugins/mission/CMakeFiles/dronecode_sdk_mission.dir/build.make plugins/mission/CMakeFiles/dronecode_sdk_mission.dir/build
.PHONY : dronecode_sdk_mission/fast

#=============================================================================
# Target rules for targets named json11

# Build rule for target.
json11: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 json11
.PHONY : json11

# fast build rule for target.
json11/fast:
	$(MAKE) -f plugins/mission/third_party/json11/CMakeFiles/json11.dir/build.make plugins/mission/third_party/json11/CMakeFiles/json11.dir/build
.PHONY : json11/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_offboard

# Build rule for target.
dronecode_sdk_offboard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_offboard
.PHONY : dronecode_sdk_offboard

# fast build rule for target.
dronecode_sdk_offboard/fast:
	$(MAKE) -f plugins/offboard/CMakeFiles/dronecode_sdk_offboard.dir/build.make plugins/offboard/CMakeFiles/dronecode_sdk_offboard.dir/build
.PHONY : dronecode_sdk_offboard/fast

#=============================================================================
# Target rules for targets named dronecode_sdk_telemetry

# Build rule for target.
dronecode_sdk_telemetry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dronecode_sdk_telemetry
.PHONY : dronecode_sdk_telemetry

# fast build rule for target.
dronecode_sdk_telemetry/fast:
	$(MAKE) -f plugins/telemetry/CMakeFiles/dronecode_sdk_telemetry.dir/build.make plugins/telemetry/CMakeFiles/dronecode_sdk_telemetry.dir/build
.PHONY : dronecode_sdk_telemetry/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f third_party/gtest/googlemock/CMakeFiles/gmock.dir/build.make third_party/gtest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f third_party/gtest/googlemock/CMakeFiles/gmock_main.dir/build.make third_party/gtest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f third_party/gtest/googlemock/gtest/CMakeFiles/gtest.dir/build.make third_party/gtest/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f third_party/gtest/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make third_party/gtest/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f integration_tests/CMakeFiles/check.dir/build.make integration_tests/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named integration_tests_runner

# Build rule for target.
integration_tests_runner: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 integration_tests_runner
.PHONY : integration_tests_runner

# fast build rule for target.
integration_tests_runner/fast:
	$(MAKE) -f integration_tests/CMakeFiles/integration_tests_runner.dir/build.make integration_tests/CMakeFiles/integration_tests_runner.dir/build
.PHONY : integration_tests_runner/fast

core/any_test.o: core/any_test.cpp.o

.PHONY : core/any_test.o

# target to build an object file
core/any_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/any_test.cpp.o
.PHONY : core/any_test.cpp.o

core/any_test.i: core/any_test.cpp.i

.PHONY : core/any_test.i

# target to preprocess a source file
core/any_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/any_test.cpp.i
.PHONY : core/any_test.cpp.i

core/any_test.s: core/any_test.cpp.s

.PHONY : core/any_test.s

# target to generate assembly for a file
core/any_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/any_test.cpp.s
.PHONY : core/any_test.cpp.s

core/call_every_handler_test.o: core/call_every_handler_test.cpp.o

.PHONY : core/call_every_handler_test.o

# target to build an object file
core/call_every_handler_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/call_every_handler_test.cpp.o
.PHONY : core/call_every_handler_test.cpp.o

core/call_every_handler_test.i: core/call_every_handler_test.cpp.i

.PHONY : core/call_every_handler_test.i

# target to preprocess a source file
core/call_every_handler_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/call_every_handler_test.cpp.i
.PHONY : core/call_every_handler_test.cpp.i

core/call_every_handler_test.s: core/call_every_handler_test.cpp.s

.PHONY : core/call_every_handler_test.s

# target to generate assembly for a file
core/call_every_handler_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/call_every_handler_test.cpp.s
.PHONY : core/call_every_handler_test.cpp.s

core/cli_arg_test.o: core/cli_arg_test.cpp.o

.PHONY : core/cli_arg_test.o

# target to build an object file
core/cli_arg_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/cli_arg_test.cpp.o
.PHONY : core/cli_arg_test.cpp.o

core/cli_arg_test.i: core/cli_arg_test.cpp.i

.PHONY : core/cli_arg_test.i

# target to preprocess a source file
core/cli_arg_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/cli_arg_test.cpp.i
.PHONY : core/cli_arg_test.cpp.i

core/cli_arg_test.s: core/cli_arg_test.cpp.s

.PHONY : core/cli_arg_test.s

# target to generate assembly for a file
core/cli_arg_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/cli_arg_test.cpp.s
.PHONY : core/cli_arg_test.cpp.s

core/curl_test.o: core/curl_test.cpp.o

.PHONY : core/curl_test.o

# target to build an object file
core/curl_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/curl_test.cpp.o
.PHONY : core/curl_test.cpp.o

core/curl_test.i: core/curl_test.cpp.i

.PHONY : core/curl_test.i

# target to preprocess a source file
core/curl_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/curl_test.cpp.i
.PHONY : core/curl_test.cpp.i

core/curl_test.s: core/curl_test.cpp.s

.PHONY : core/curl_test.s

# target to generate assembly for a file
core/curl_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/curl_test.cpp.s
.PHONY : core/curl_test.cpp.s

core/global_include_test.o: core/global_include_test.cpp.o

.PHONY : core/global_include_test.o

# target to build an object file
core/global_include_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/global_include_test.cpp.o
.PHONY : core/global_include_test.cpp.o

core/global_include_test.i: core/global_include_test.cpp.i

.PHONY : core/global_include_test.i

# target to preprocess a source file
core/global_include_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/global_include_test.cpp.i
.PHONY : core/global_include_test.cpp.i

core/global_include_test.s: core/global_include_test.cpp.s

.PHONY : core/global_include_test.s

# target to generate assembly for a file
core/global_include_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/global_include_test.cpp.s
.PHONY : core/global_include_test.cpp.s

core/locked_queue_test.o: core/locked_queue_test.cpp.o

.PHONY : core/locked_queue_test.o

# target to build an object file
core/locked_queue_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/locked_queue_test.cpp.o
.PHONY : core/locked_queue_test.cpp.o

core/locked_queue_test.i: core/locked_queue_test.cpp.i

.PHONY : core/locked_queue_test.i

# target to preprocess a source file
core/locked_queue_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/locked_queue_test.cpp.i
.PHONY : core/locked_queue_test.cpp.i

core/locked_queue_test.s: core/locked_queue_test.cpp.s

.PHONY : core/locked_queue_test.s

# target to generate assembly for a file
core/locked_queue_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/locked_queue_test.cpp.s
.PHONY : core/locked_queue_test.cpp.s

core/mavlink_channels_test.o: core/mavlink_channels_test.cpp.o

.PHONY : core/mavlink_channels_test.o

# target to build an object file
core/mavlink_channels_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/mavlink_channels_test.cpp.o
.PHONY : core/mavlink_channels_test.cpp.o

core/mavlink_channels_test.i: core/mavlink_channels_test.cpp.i

.PHONY : core/mavlink_channels_test.i

# target to preprocess a source file
core/mavlink_channels_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/mavlink_channels_test.cpp.i
.PHONY : core/mavlink_channels_test.cpp.i

core/mavlink_channels_test.s: core/mavlink_channels_test.cpp.s

.PHONY : core/mavlink_channels_test.s

# target to generate assembly for a file
core/mavlink_channels_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/mavlink_channels_test.cpp.s
.PHONY : core/mavlink_channels_test.cpp.s

core/thread_pool_test.o: core/thread_pool_test.cpp.o

.PHONY : core/thread_pool_test.o

# target to build an object file
core/thread_pool_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/thread_pool_test.cpp.o
.PHONY : core/thread_pool_test.cpp.o

core/thread_pool_test.i: core/thread_pool_test.cpp.i

.PHONY : core/thread_pool_test.i

# target to preprocess a source file
core/thread_pool_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/thread_pool_test.cpp.i
.PHONY : core/thread_pool_test.cpp.i

core/thread_pool_test.s: core/thread_pool_test.cpp.s

.PHONY : core/thread_pool_test.s

# target to generate assembly for a file
core/thread_pool_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/thread_pool_test.cpp.s
.PHONY : core/thread_pool_test.cpp.s

core/timeout_handler_test.o: core/timeout_handler_test.cpp.o

.PHONY : core/timeout_handler_test.o

# target to build an object file
core/timeout_handler_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/timeout_handler_test.cpp.o
.PHONY : core/timeout_handler_test.cpp.o

core/timeout_handler_test.i: core/timeout_handler_test.cpp.i

.PHONY : core/timeout_handler_test.i

# target to preprocess a source file
core/timeout_handler_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/timeout_handler_test.cpp.i
.PHONY : core/timeout_handler_test.cpp.i

core/timeout_handler_test.s: core/timeout_handler_test.cpp.s

.PHONY : core/timeout_handler_test.s

# target to generate assembly for a file
core/timeout_handler_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/timeout_handler_test.cpp.s
.PHONY : core/timeout_handler_test.cpp.s

core/unittests_main.o: core/unittests_main.cpp.o

.PHONY : core/unittests_main.o

# target to build an object file
core/unittests_main.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/unittests_main.cpp.o
.PHONY : core/unittests_main.cpp.o

core/unittests_main.i: core/unittests_main.cpp.i

.PHONY : core/unittests_main.i

# target to preprocess a source file
core/unittests_main.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/unittests_main.cpp.i
.PHONY : core/unittests_main.cpp.i

core/unittests_main.s: core/unittests_main.cpp.s

.PHONY : core/unittests_main.s

# target to generate assembly for a file
core/unittests_main.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/core/unittests_main.cpp.s
.PHONY : core/unittests_main.cpp.s

plugins/calibration/calibration_statustext_parser_test.o: plugins/calibration/calibration_statustext_parser_test.cpp.o

.PHONY : plugins/calibration/calibration_statustext_parser_test.o

# target to build an object file
plugins/calibration/calibration_statustext_parser_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/plugins/calibration/calibration_statustext_parser_test.cpp.o
.PHONY : plugins/calibration/calibration_statustext_parser_test.cpp.o

plugins/calibration/calibration_statustext_parser_test.i: plugins/calibration/calibration_statustext_parser_test.cpp.i

.PHONY : plugins/calibration/calibration_statustext_parser_test.i

# target to preprocess a source file
plugins/calibration/calibration_statustext_parser_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/plugins/calibration/calibration_statustext_parser_test.cpp.i
.PHONY : plugins/calibration/calibration_statustext_parser_test.cpp.i

plugins/calibration/calibration_statustext_parser_test.s: plugins/calibration/calibration_statustext_parser_test.cpp.s

.PHONY : plugins/calibration/calibration_statustext_parser_test.s

# target to generate assembly for a file
plugins/calibration/calibration_statustext_parser_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/plugins/calibration/calibration_statustext_parser_test.cpp.s
.PHONY : plugins/calibration/calibration_statustext_parser_test.cpp.s

plugins/camera/camera_definition_test.o: plugins/camera/camera_definition_test.cpp.o

.PHONY : plugins/camera/camera_definition_test.o

# target to build an object file
plugins/camera/camera_definition_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/plugins/camera/camera_definition_test.cpp.o
.PHONY : plugins/camera/camera_definition_test.cpp.o

plugins/camera/camera_definition_test.i: plugins/camera/camera_definition_test.cpp.i

.PHONY : plugins/camera/camera_definition_test.i

# target to preprocess a source file
plugins/camera/camera_definition_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/plugins/camera/camera_definition_test.cpp.i
.PHONY : plugins/camera/camera_definition_test.cpp.i

plugins/camera/camera_definition_test.s: plugins/camera/camera_definition_test.cpp.s

.PHONY : plugins/camera/camera_definition_test.s

# target to generate assembly for a file
plugins/camera/camera_definition_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/plugins/camera/camera_definition_test.cpp.s
.PHONY : plugins/camera/camera_definition_test.cpp.s

plugins/mission/mission_import_qgc_test.o: plugins/mission/mission_import_qgc_test.cpp.o

.PHONY : plugins/mission/mission_import_qgc_test.o

# target to build an object file
plugins/mission/mission_import_qgc_test.cpp.o:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/plugins/mission/mission_import_qgc_test.cpp.o
.PHONY : plugins/mission/mission_import_qgc_test.cpp.o

plugins/mission/mission_import_qgc_test.i: plugins/mission/mission_import_qgc_test.cpp.i

.PHONY : plugins/mission/mission_import_qgc_test.i

# target to preprocess a source file
plugins/mission/mission_import_qgc_test.cpp.i:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/plugins/mission/mission_import_qgc_test.cpp.i
.PHONY : plugins/mission/mission_import_qgc_test.cpp.i

plugins/mission/mission_import_qgc_test.s: plugins/mission/mission_import_qgc_test.cpp.s

.PHONY : plugins/mission/mission_import_qgc_test.s

# target to generate assembly for a file
plugins/mission/mission_import_qgc_test.cpp.s:
	$(MAKE) -f CMakeFiles/unit_tests_runner.dir/build.make CMakeFiles/unit_tests_runner.dir/plugins/mission/mission_import_qgc_test.cpp.s
.PHONY : plugins/mission/mission_import_qgc_test.cpp.s

src/CYdLidar.o: src/CYdLidar.cpp.o

.PHONY : src/CYdLidar.o

# target to build an object file
src/CYdLidar.cpp.o:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/CYdLidar.cpp.o
.PHONY : src/CYdLidar.cpp.o

src/CYdLidar.i: src/CYdLidar.cpp.i

.PHONY : src/CYdLidar.i

# target to preprocess a source file
src/CYdLidar.cpp.i:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/CYdLidar.cpp.i
.PHONY : src/CYdLidar.cpp.i

src/CYdLidar.s: src/CYdLidar.cpp.s

.PHONY : src/CYdLidar.s

# target to generate assembly for a file
src/CYdLidar.cpp.s:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/CYdLidar.cpp.s
.PHONY : src/CYdLidar.cpp.s

src/impl/unix/unix_serial.o: src/impl/unix/unix_serial.cpp.o

.PHONY : src/impl/unix/unix_serial.o

# target to build an object file
src/impl/unix/unix_serial.cpp.o:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/impl/unix/unix_serial.cpp.o
.PHONY : src/impl/unix/unix_serial.cpp.o

src/impl/unix/unix_serial.i: src/impl/unix/unix_serial.cpp.i

.PHONY : src/impl/unix/unix_serial.i

# target to preprocess a source file
src/impl/unix/unix_serial.cpp.i:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/impl/unix/unix_serial.cpp.i
.PHONY : src/impl/unix/unix_serial.cpp.i

src/impl/unix/unix_serial.s: src/impl/unix/unix_serial.cpp.s

.PHONY : src/impl/unix/unix_serial.s

# target to generate assembly for a file
src/impl/unix/unix_serial.cpp.s:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/impl/unix/unix_serial.cpp.s
.PHONY : src/impl/unix/unix_serial.cpp.s

src/impl/unix/unix_timer.o: src/impl/unix/unix_timer.cpp.o

.PHONY : src/impl/unix/unix_timer.o

# target to build an object file
src/impl/unix/unix_timer.cpp.o:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/impl/unix/unix_timer.cpp.o
.PHONY : src/impl/unix/unix_timer.cpp.o

src/impl/unix/unix_timer.i: src/impl/unix/unix_timer.cpp.i

.PHONY : src/impl/unix/unix_timer.i

# target to preprocess a source file
src/impl/unix/unix_timer.cpp.i:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/impl/unix/unix_timer.cpp.i
.PHONY : src/impl/unix/unix_timer.cpp.i

src/impl/unix/unix_timer.s: src/impl/unix/unix_timer.cpp.s

.PHONY : src/impl/unix/unix_timer.s

# target to generate assembly for a file
src/impl/unix/unix_timer.cpp.s:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/impl/unix/unix_timer.cpp.s
.PHONY : src/impl/unix/unix_timer.cpp.s

src/serial.o: src/serial.cpp.o

.PHONY : src/serial.o

# target to build an object file
src/serial.cpp.o:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/serial.cpp.o
.PHONY : src/serial.cpp.o

src/serial.i: src/serial.cpp.i

.PHONY : src/serial.i

# target to preprocess a source file
src/serial.cpp.i:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/serial.cpp.i
.PHONY : src/serial.cpp.i

src/serial.s: src/serial.cpp.s

.PHONY : src/serial.s

# target to generate assembly for a file
src/serial.cpp.s:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/serial.cpp.s
.PHONY : src/serial.cpp.s

src/ydlidar_driver.o: src/ydlidar_driver.cpp.o

.PHONY : src/ydlidar_driver.o

# target to build an object file
src/ydlidar_driver.cpp.o:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/ydlidar_driver.cpp.o
.PHONY : src/ydlidar_driver.cpp.o

src/ydlidar_driver.i: src/ydlidar_driver.cpp.i

.PHONY : src/ydlidar_driver.i

# target to preprocess a source file
src/ydlidar_driver.cpp.i:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/ydlidar_driver.cpp.i
.PHONY : src/ydlidar_driver.cpp.i

src/ydlidar_driver.s: src/ydlidar_driver.cpp.s

.PHONY : src/ydlidar_driver.s

# target to generate assembly for a file
src/ydlidar_driver.cpp.s:
	$(MAKE) -f CMakeFiles/ydlidar_driver.dir/build.make CMakeFiles/ydlidar_driver.dir/src/ydlidar_driver.cpp.s
.PHONY : src/ydlidar_driver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... ydlidar_driver"
	@echo "... unit_tests_runner"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... uninstall"
	@echo "... xmltest"
	@echo "... tinyxml2_static"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousMemCheck"
	@echo "... Nightly"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... Continuous"
	@echo "... NightlyBuild"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ContinuousConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... Experimental"
	@echo "... NightlySubmit"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousStart"
	@echo "... ContinuousUpdate"
	@echo "... minigzip"
	@echo "... example"
	@echo "... zlibstatic"
	@echo "... zlib"
	@echo "... example64"
	@echo "... minigzip64"
	@echo "... ydlidar_test"
	@echo "... cpp_rsc"
	@echo "... dronecode_sdk"
	@echo "... dronecode_sdk_action"
	@echo "... dronecode_sdk_calibration"
	@echo "... camera_definition_files"
	@echo "... dronecode_sdk_camera"
	@echo "... dronecode_sdk_follow_me"
	@echo "... dronecode_sdk_gimbal"
	@echo "... dronecode_sdk_info"
	@echo "... dronecode_sdk_log_files"
	@echo "... dronecode_sdk_mission"
	@echo "... json11"
	@echo "... dronecode_sdk_offboard"
	@echo "... dronecode_sdk_telemetry"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... check"
	@echo "... integration_tests_runner"
	@echo "... core/any_test.o"
	@echo "... core/any_test.i"
	@echo "... core/any_test.s"
	@echo "... core/call_every_handler_test.o"
	@echo "... core/call_every_handler_test.i"
	@echo "... core/call_every_handler_test.s"
	@echo "... core/cli_arg_test.o"
	@echo "... core/cli_arg_test.i"
	@echo "... core/cli_arg_test.s"
	@echo "... core/curl_test.o"
	@echo "... core/curl_test.i"
	@echo "... core/curl_test.s"
	@echo "... core/global_include_test.o"
	@echo "... core/global_include_test.i"
	@echo "... core/global_include_test.s"
	@echo "... core/locked_queue_test.o"
	@echo "... core/locked_queue_test.i"
	@echo "... core/locked_queue_test.s"
	@echo "... core/mavlink_channels_test.o"
	@echo "... core/mavlink_channels_test.i"
	@echo "... core/mavlink_channels_test.s"
	@echo "... core/thread_pool_test.o"
	@echo "... core/thread_pool_test.i"
	@echo "... core/thread_pool_test.s"
	@echo "... core/timeout_handler_test.o"
	@echo "... core/timeout_handler_test.i"
	@echo "... core/timeout_handler_test.s"
	@echo "... core/unittests_main.o"
	@echo "... core/unittests_main.i"
	@echo "... core/unittests_main.s"
	@echo "... plugins/calibration/calibration_statustext_parser_test.o"
	@echo "... plugins/calibration/calibration_statustext_parser_test.i"
	@echo "... plugins/calibration/calibration_statustext_parser_test.s"
	@echo "... plugins/camera/camera_definition_test.o"
	@echo "... plugins/camera/camera_definition_test.i"
	@echo "... plugins/camera/camera_definition_test.s"
	@echo "... plugins/mission/mission_import_qgc_test.o"
	@echo "... plugins/mission/mission_import_qgc_test.i"
	@echo "... plugins/mission/mission_import_qgc_test.s"
	@echo "... src/CYdLidar.o"
	@echo "... src/CYdLidar.i"
	@echo "... src/CYdLidar.s"
	@echo "... src/impl/unix/unix_serial.o"
	@echo "... src/impl/unix/unix_serial.i"
	@echo "... src/impl/unix/unix_serial.s"
	@echo "... src/impl/unix/unix_timer.o"
	@echo "... src/impl/unix/unix_timer.i"
	@echo "... src/impl/unix/unix_timer.s"
	@echo "... src/serial.o"
	@echo "... src/serial.i"
	@echo "... src/serial.s"
	@echo "... src/ydlidar_driver.o"
	@echo "... src/ydlidar_driver.i"
	@echo "... src/ydlidar_driver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

